import { TooltipProvider } from "@/components/ui/tooltip";
import TanstackProvider from "@/providers/TanstackProvider";
import { ContextProviders } from "@/redux/provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import dotenv from 'dotenv';
dotenv.config();
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackProvider>
          <ContextProviders>
            <TooltipProvider>
              {children}
            </TooltipProvider>
          </ContextProviders>
        </TanstackProvider>
      </body>
    </html>
  );
}
