import {
  TooltipProvider
} from "@/components/ui/tooltip";

import TanstackProvider from "@/providers/TanstackProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { ContextProviders } from "@/redux/provider";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // you can include other weights too
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={roboto.className} >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        ><TanstackProvider>
            <ContextProviders>
              <TooltipProvider>
                {children}
              </TooltipProvider>
            </ContextProviders>
          </TanstackProvider>
        </ ThemeProvider>
      </body>
    </html>
  );
}
