import Footer from "@/components/common/footer/Footer";
import Header from "@/components/common/header/Header";
import { TooltipProvider } from "@/components/ui/tooltip";
import TanstackProvider from "@/providers/TanstackProvider";
import { ContextProviders } from "@/redux/provider";
import type { Metadata } from "next";
import { Fira_Code, Marck_Script, Outfit } from "next/font/google";
import "./globals.css";

import { Providers } from "@/providers/providers";

// Font imports from Google Fonts
const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-fira-code",
  display: "swap",
});

const marckScript = Marck_Script({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-marck-script",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.variable} ${firaCode.variable} ${marckScript.variable} antialiased`}
      >
        <TanstackProvider>
          <ContextProviders>
            <TooltipProvider>
              <Providers>
                <Header />
                {children}
                <Footer />
              </Providers>
            </TooltipProvider>
          </ContextProviders>
        </TanstackProvider>
      </body>
    </html>
  );
}
